version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
  worker:
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - "redis"
